### ISSUE TITLE
Cards are not positioned correctly

### ISSUE THREAD

**Issue by liammalby** [liammalby/WebDevPractice-TinDog#1]
Under the heading 'A Plan for Every Dog's Needs', the cards are not responsive in the way I would like. I would like them to behave in the same way that the Bootstrap example does: [Bootstrap Example](https://getbootstrap.com/docs/5.1/examples/pricing/).

**Comment by NevilleMthw** [comment]
Hi, can I handle this issue if it is not yet assigned or completed?

**Comment by NevilleMthw** [comment]
I have submitted a PR (pull request) for the issue.
