### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by liammalby** [liammalby/WebDevPractice-TinDog#2]
Lots of unnecessary and messy code. Need to refactor styles.css and probably index.html too.

**Comment by NevilleMthw** [comment]
Hi, by refactoring, do you want to improve the overall code structure?

**Comment by liammalby** [comment]
Yep! I'm building this website as a learning tool really, and after following along with the tutorial the code has become pretty messy. I would be interested in seeing how it looks once the structure is improved.

**Comment by NevilleMthw** [comment]
Alright, I will try and see what can be improved.
